name: env_tutorial 
## Triggers the workflow on when there is a push, or 
## pull request on the main branch on: [pull_request, push] 
on: [pull_request, push]

env:
## Sets environment 
  variable API_KEY: "XXXXXXXXXXXX"

jobs: 
  ## The type of runner that the job will run on,
  ## here it runs on ubuntu latest 
  job1:
    runs-on: ubuntu-latest 
    steps: 
    - name: step 1 
    ## Reference your environment variables run: echo "The API key is:${{env.API_KEY}}"
      run: echo "The API key is:$API_KEY"
